include: package:effective_dart/analysis_options.1.2.0.yaml

linter:
  rules:
    public_member_api_docs: false
    constant_identifier_names: false
    one_member_abstracts: false
    directives_ordering: false
    prefer_const_constructors: true
    type_annotate_public_apis: false

analyzer:
  errors:
    prefer_const_constructors: error
    unrecognized_error_code: ignore
    asset_does_not_exist: ignore