const ERROR_EMAIL_ALREADY_IN_USE = 'ERROR_EMAIL_ALREADY_IN_USE';
const ERROR_WEAK_PASSWORD = 'ERROR_WEAK_PASSWORD';
const ERROR_INVALID_EMAIL = 'ERROR_INVALID_EMAIL';
const ERROR_WRONG_PASSWORD = 'ERROR_WRONG_PASSWORD';
